### ISSUE TITLE
Windows and Linux Support

### ISSUE THREAD

**Issue by dominicap** [dominicap/auto-tune#4]
Need to use ffmpeg instead of afconvert to convert to aac.

**Comment by shillshocked** [comment]
It partially works

On Linux, when I run it I get:

`home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/lib/autotune/util.rb:36:in `os': Operation not permitted - Operating System is not supported (Errno::EPERM)
	from /home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/exe/autotune:72:in `<top (required)>'
	from /home/destiny/.gem/ruby/2.4.0/bin/autotune:23:in `load'
	from /home/destiny/.gem/ruby/2.4.0/bin/autotune:23:in `<main>'`

I can change util.rb to default all to macos (as linux is not an option). When I do that, I get:

`/home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/lib/autotune/designator.rb:259:in `from_int': Expected argument 0 of type int, but got Hash {"20"=>{"name"=>"Alternative",... (TypeError)
	in SWIG method 'TagLib_MP4_Item_from_int'
	from /home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/lib/autotune/designator.rb:259:in `block in set_genre_id'
	from /home/destiny/.gem/ruby/2.4.0/gems/taglib-ruby-0.7.1/lib/taglib/base.rb:8:in `open'
	from /home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/lib/autotune/designator.rb:257:in `set_genre_id'
	from /home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/lib/autotune/designator.rb:313:in `set_all'
	from /home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/exe/autotune:101:in `block in <top (required)>'
	from /home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/exe/autotune:91:in `each'
	from /home/destiny/.gem/ruby/2.4.0/gems/autotune-0.1.0/exe/autotune:91:in `<top (required)>'`
	from /home/destiny/.gem/ruby/2.4.0/bin/autotune:23:in `load'
	from /home/destiny/.gem/ruby/2.4.0/bin/autotune:23:in `<main>'

As far as I can tell, this album has multiple genres, but the program is expecting only one. That is where it crashes.

**Comment by shillshocked** [comment]
I was able to get it to work by commenting out these lines in designator.rb around that error:

```
 #       if song =~ /.*\.M4A$/i
 #         TagLib::MP4::File.open(song) do |tune|
 #           unless genre_id.nil?
 #             item = TagLib::MP4::Item.from_int(genre_id)
 #             tune.tag.item_list_map.insert('geID', item)
 #             tune.save
 #           end
 #         end
 #       end
```
